# Generated by Django 3.2.4 on 2021-06-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartclock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='icon_data',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='icon_data',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
