# Generated by Django 3.2.4 on 2021-06-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartclock', '0002_auto_20210627_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='icon_data',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
