# Generated by Django 3.2.4 on 2021-06-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartclock', '0003_alter_room_icon_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='icon_data',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='icon_data',
            field=models.IntegerField(null=True),
        ),
    ]
