# Generated by Django 3.2.4 on 2021-06-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartclock', '0004_auto_20210628_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
