# Generated by Django 3.2.4 on 2021-09-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartclock', '0006_alarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('status', models.BooleanField()),
                ('automatedtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartclock.automatedtask')),
            ],
        ),
    ]
