# Generated by Django 3.2.4 on 2021-09-30 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartclock', '0008_alter_task_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartclock.room'),
        ),
    ]
