# Generated by Django 3.2.4 on 2021-09-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartclock', '0010_remove_task_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='to_do',
            field=models.BooleanField(default=False),
        ),
    ]
